### ISSUE TITLE
Installation Broken

### ISSUE THREAD

**Issue by spirritus** [andy-portmen/native-client#65]
.. Writting to Chrome Registry
.. Key: HKCU\Software\Google\Chrome\NativeMessagingHosts\com.add0n.node
Der Vorgang wurde erfolgreich beendet.
.. Writting to Firefox Registry
.. Key: HKCU\SOFTWARE\Mozilla\NativeMessagingHosts\com.add0n.node
Der Vorgang wurde erfolgreich beendet.
Y:\05-Software\01-Workstations\01-Grundausstattung\05-NetzwerkuInternet\BrowserOpenWithAddOn\native-client-master\windows\app\config.js:1
(function (exports, require, module, __filename, __dirname) { ../../config.js
                                                              ^
SyntaxError: Unexpected token .
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (Y:\05-Software\01-Workstations\01-Grundausstattung\05-NetzwerkuInternet\BrowserOpenWithAddOn\native-client-master\windows\app\install
.js:20:33)
Drücken Sie eine beliebige Taste . . .

**Comment by andy-portmen** [comment]
What is your windows version?

**Comment by andy-portmen** [comment]
It seems you have cloned the native client from the GitHub repo. You should use https://github.com/andy-portmen/native-client/releases to get the latest version. If you want to directly use the cloned version in Windows os, first fix the symlinks.
